### PR TITLE
Solved issue #166

### PR DESCRIPTION
**Pull request by GamerWhoDoesntGame**
Updated badges in README.md with cooler badges.

### CODE REVIEW

**Comment by osBins** [comment]
Great! Thanks for the PR @GamerWhoDoesntGame.

However, I just noticed that white font over the yellow badge isn't readable. Can you change the 'issues' and 'pull requests' badge colour to something (try green?) which makes the text on it easily readable?

**Comment by GamerWhoDoesntGame** [comment]
Ok, I'm on it.

**Comment by GamerWhoDoesntGame** [comment]
I added it. You can have a look.

**Comment by osBins** [comment]
Great work @GamerWhoDoesntGame!

**Pull request merged**
